CREATE TABLE `t_student` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_bin',
	`sno` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '学号' COLLATE 'utf8_bin',
	`gender` INT(11) NOT NULL COMMENT '1=男,2=女',
	`age` INT(11) NOT NULL,
	`created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `sno` (`sno`),
	INDEX `name` (`name`),
	INDEX `age` (`age`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=3;
